name = "golars"
grammar = "golars"
path_suffixes = ["glr"]
line_comments = ["# "]
autoclose_before = ";:.,=}])\">"
tab_size = 2
hard_tabs = false

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]

word_characters = ["/", "-", "."]
